name: Main
on:
  push:
    tags:
      - '*'

jobs:
  build:
    if:      "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'
          architecture: 'x64'
      - run:  |
              pip install -r requirements.txt
              pelican content -s publishconf.py 
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build.zip"
